config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles

  root 'static_pages#home'
  namespace :admin do
    resources :part_ones
    resources :part_twos
    resources :part_threes
    resources :part_fours
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :answer_sheet

  scope :index, -> { all }
end

app/models/answer_sheet.rb
class AnswerSheet < ApplicationRecord
  belongs_to :examination
  belongs_to :examinee, class_name: "User"
  has_many :answers

  scope :index, -> { all }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  scope :index, -> { all }
end

app/models/examination.rb
class Examination < ApplicationRecord
  has_many :questions, through: :examination_questions
  has_many :examination_questions
  has_many :examinees, class_name: "AnswerSheet", foreign_key: "examinee_id"
  has_many :answer_sheets
  belongs_to :creator, class_name: "User"

  scope :index, -> { all }
end

app/models/examination_question.rb
class ExaminationQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :examination
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :sub_question, optional: true
end

app/models/part_five.rb
class PartFive < Question
  scope :index, -> { all }
end

app/models/part_four.rb
class PartFour < Question
  mount_uploader :audio, AudioUploader

  has_many :sub_questions, as: :resource, dependent: :destroy

  validates :audio, presence: true

  scope :index, -> { all }

  accepts_nested_attributes_for :sub_questions
end

app/models/part_one.rb
class PartOne < Question
  mount_uploader :audio, AudioUploader
  mount_uploader :photo, PhotoUploader

  validates :correct_option, presence: true
  validates :audio, presence: true
  validates :photo, presence: true

  scope :index, -> { all }
end

app/models/part_seven_one.rb
class PartSevenOne < Question
  scope :index, -> { all }
end

app/models/part_seven_two.rb
class PartSevenTwo < Question
  scope :index, -> { all }
end

app/models/part_six.rb
class PartSix < Question
  scope :index, -> { all }
end

app/models/part_three.rb
class PartThree < Question
  mount_uploader :audio, AudioUploader

  has_many :sub_questions, as: :resource, dependent: :destroy

  validates :audio, presence: true

  scope :index, -> { all }

  accepts_nested_attributes_for :sub_questions
end

app/models/part_two.rb
class PartTwo < Question
  mount_uploader :audio, AudioUploader

  validates :correct_option, presence: true
  validates :audio, presence: true

  scope :index, -> { all }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :sub_questions

  scope :index, -> { all }

  def correct_option_s
    SysConst::PART_1_2_OPTIONS.key(correct_option)
  end

  def level_s
    SysConst::QUESTION_LEVELS_TO_S[SysConst::QUESTION_LEVELS.key(level)]
  end
end

app/models/sub_question.rb
class SubQuestion < ApplicationRecord
  belongs_to :resource, polymorphic: true, optional: true
  has_many :options

  accepts_nested_attributes_for :options
end

app/models/sys_const.rb
class SysConst
  PART_1_2_OPTIONS = {
    "A" => 1,
    "B" => 2,
    "C" => 3
  }

  QUESTION_LEVELS = {
    less_than_300: 1,
    from_300_to_450: 2,
    from_450_to_600: 3,
    from_600_to_750: 4,
    greater_than_750: 5
  }

  QUESTION_LEVELS_TO_S = {
    less_than_300: "0-300",
    from_300_to_450: "300-450",
    from_450_to_600: "450-600",
    from_600_to_750: "600-750",
    greater_than_750: "750-990",
  }

  NUMBER_OF_SUB_QUESTIONS = {
    part_three: 3,
    part_four: 3,
    part_seven_one: 5,
    part_seven_two: 5
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  [:questions, :part_ones, :part_twos, :part_threes, :part_fours, :part_fives, :part_sixs, :part_seven_ones, :part_seven_twos, :examinations].each do |object|
    has_many object, foreign_key: "creator_id"
  end

  has_many :answer_sheets, foreign_key: "examinee_id"

  scope :index, -> { all }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%#= f.label :content %>
    <%#= f.text_area :content, as: :summernote %>
    <%= f.input :content, as: :summernote %>
    <%#= f.text_area :content, "data-provider" => "summernote" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article), method: 'get' %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path, method: 'get', class: "btn btn-primary" %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content.html_safe %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>