config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles

  root 'static_pages#home'
  namespace :admin do
    resources :part_ones
    resources :part_twos
    resources :part_threes
    resources :part_fours
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :answer_sheet

  scope :index, -> { all }
end

app/models/answer_sheet.rb
class AnswerSheet < ApplicationRecord
  belongs_to :examination
  belongs_to :examinee, class_name: "User"
  has_many :answers

  scope :index, -> { all }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  scope :index, -> { all }
end

app/models/examination.rb
class Examination < ApplicationRecord
  has_many :questions, through: :examination_questions
  has_many :examination_questions
  has_many :examinees, class_name: "AnswerSheet", foreign_key: "examinee_id"
  has_many :answer_sheets
  belongs_to :creator, class_name: "User"

  scope :index, -> { all }
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :sub_question, optional: true
end

app/models/part_five.rb
class PartFive < Question
  scope :index, -> { all }
end

app/models/part_four.rb
class PartFour < Question
  mount_uploader :audio, AudioUploader

  has_many :sub_questions, as: :resource, dependent: :destroy

  validates :audio, presence: true

  scope :index, -> { all }

  accepts_nested_attributes_for :sub_questions
end

app/models/part_one.rb
class PartOne < Question
  mount_uploader :audio, AudioUploader
  mount_uploader :photo, PhotoUploader

  validates :correct_option, presence: true
  validates :audio, presence: true
  validates :photo, presence: true

  scope :index, -> { all }
end

app/models/part_seven_one.rb
class PartSevenOne < Question
  scope :index, -> { all }
end

app/models/part_seven_two.rb
class PartSevenTwo < Question
  scope :index, -> { all }
end

app/models/part_six.rb
class PartSix < Question
  scope :index, -> { all }
end

app/models/part_three.rb
class PartThree < Question
  mount_uploader :audio, AudioUploader

  has_many :sub_questions, as: :resource, dependent: :destroy

  validates :audio, presence: true

  scope :index, -> { all }

  accepts_nested_attributes_for :sub_questions
end

app/models/part_two.rb
class PartTwo < Question
  mount_uploader :audio, AudioUploader

  validates :correct_option, presence: true
  validates :audio, presence: true

  scope :index, -> { all }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :sub_questions

  scope :index, -> { all }

  def correct_option_s
    SysConst::PART_1_2_OPTIONS.key(correct_option)
  end

  def level_s
    SysConst::QUESTION_LEVELS_TO_S[SysConst::QUESTION_LEVELS.key(level)]
  end
end

app/models/sub_question.rb
class SubQuestion < ApplicationRecord
  belongs_to :resource, polymorphic: true, optional: true
  has_many :options

  accepts_nested_attributes_for :options
end

app/models/sys_const.rb
class SysConst
  PART_1_2_OPTIONS = {
    "A" => 1,
    "B" => 2,
    "C" => 3
  }

  QUESTION_LEVELS = {
    less_than_300: 1,
    from_300_to_450: 2,
    from_450_to_600: 3,
    from_600_to_750: 4,
    greater_than_750: 5
  }

  QUESTION_LEVELS_TO_S = {
    less_than_300: "0-300",
    from_300_to_450: "300-450",
    from_450_to_600: "450-600",
    from_600_to_750: "600-750",
    greater_than_750: "750-990",
  }

  NUMBER_OF_SUB_QUESTIONS = {
    part_three: 3,
    part_four: 3,
    part_seven_one: 5,
    part_seven_two: 5
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  [:questions, :part_ones, :part_twos, :part_threes, :part_fours, :part_fives, :part_sixs, :part_seven_ones, :part_seven_twos, :examinations].each do |object|
    has_many object, foreign_key: "creator_id"
  end

  has_many :answer_sheets, foreign_key: "examinee_id"

  scope :index, -> { all }
end

app/controllers/admin/part_twos_controller.rb
class Admin::PartTwosController < ApplicationController
  include StandardActions

  def index
    standard_index
  end

  def show
    standard_show
  end

  def new
    standard_new
  end

  def create
    standard_create
  end

  def edit
    standard_edit
  end

  def update
    standard_update
  end

  def destroy
    standard_destroy
  end

  private
  def permit_params
    params.fetch(:part_two, {}).permit(:audio, :photo, :correct_option, :level)
  end
end

app/helpers/admin/part_twos_helper.rb
module Admin::PartTwosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/part_twos/_form.html.erb
<%= form_for([:admin, @part_two]) do |f| %>
  <%= render "shared/error_messages", object: @part_two %>

  <div class="field">
    <%= f.label :audio, :class => 'control-label' %>
    <%= f.file_field :audio %>
  </div>

  <b>Correct Option: </b> <br>
  <% SysConst::PART_1_2_OPTIONS.each do |option, value| %>
    <b><%= option %>: </b><%= f.radio_button :correct_option, value, required: true %> </br>
  <% end %>
  <b>Level: </b>

  <div class="field">
    <%= f.select(:level, SysConst::QUESTION_LEVELS.collect {|level, value| [SysConst::QUESTION_LEVELS_TO_S[level], value]}, :prompt => 'Select') %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/part_twos/edit.html.erb
<%= render "form" %>

app/views/admin/part_twos/index.html.erb
<ul>
  <% @part_twos.each do |part_two| %>
    <%= audio_tag part_two.audio, controls: true %> |
    <%= link_to "show", admin_part_two_path(part_two) %> |
    <%= link_to "edit", edit_admin_part_two_path(part_two) %> |
    <%= link_to "delete", admin_part_two_path(part_two), method: :delete,
          data: { confirm: 'Are you sure?' } %> <br>
  <% end %>
</ul>

app/views/admin/part_twos/show.html.erb
<%= audio_tag @part_two.audio, controls: true %>
<br>
Correct Option: <%= @part_two.correct_option_s %>